name: Run Ryanair Parser

on: 
  workflow_dispatch:       # позволяет запускать вручную кнопкой

jobs:
  run-parser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests telethon python-dotenv urllib3

      - name: Run parser
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          USER_ID: ${{ secrets.USER_ID }}
          RYANAIR_COOKIE: ${{ secrets.RYANAIR_COOKIE }}
          STRING_SESSION: ${{ secrets.STRING_SESSION }}

        run: |
          python Projects/ryanair_parcer/ryanair_parcer.py 
